# name属性用来指定这个工作流的名字
name: Download Nodes

on:
  push:
    branches:
      - main
  schedule:   
    - cron: '0 */6 * * *'

jobs:
  run-csjs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main  #采用main分支下的
      - name: Prepare Env
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo hwclock --systohc
      - name: Download the subscribe
        run: |
          bash ./run.sh
      - name: Commit Changes
        run: |
         git config --global user.email admin@zkyml.com
         git config --global user.name zkyml
         git add .
         if git diff-index --quiet HEAD; then
            echo "no file need to commit"
         else
            time=`date "+%Y-%m-%d %H:%M:%S"`
            git commit -m "commit by github actions,date:$time"
         fi
         git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force_with_lease: true
          directory: .
