# name属性用来指定这个工作流的名字
name: Download Nodes

on:
  push:
    branches:
      - main
  schedule:   
    - cron: '0 */6 * * *'

jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
      - name: Download the subscribe
        run: |
          sh ./run.sh
      - name: Commit Changes
        run: |
         git config --global user.email admin@zkyml.com
         git config --global user.name zkyml
         git add .
         if git diff-index --quiet HEAD; then
            echo "没有未提交的改动"
         else
            echo "有未提交的改动"
            cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
            sudo hwclock --systohc
            git commit -m "由github actions推送,日期:`date +%Y%m%d`"
         fi
         git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force_with_lease: true
          directory: .
